export const CROPS = {
    "தானியங்கள் | Cereals": [
        { n: "நெல் | Paddy", e: "🌾", s: "Jun–Oct", r: "All India" },
        { n: "கோதுமை | Wheat", e: "🌾", s: "Nov–Mar", r: "North India" },
        { n: "மக்காச்சோளம் | Maize", e: "🌽", s: "Jun–Sep", r: "All India" },
        { n: "ராகி | Ragi", e: "🌾", s: "Jun–Sep", r: "Karnataka, TN" },
        { n: "சோளம் | Jowar", e: "🌾", s: "Jun–Sep", r: "Maharashtra" },
        { n: "கம்பு | Bajra", e: "🌾", s: "Jun–Sep", r: "Rajasthan" },
        { n: "வரகு | Kodo Millet", e: "🌾", s: "Jun–Sep", r: "MP, CG" },
        { n: "சாமை | Little Millet", e: "🌾", s: "Jun–Sep", r: "South India" },
        { n: "தினை | Foxtail Millet", e: "🌾", s: "Jun–Sep", r: "AP, TN" },
        { n: "Barley", e: "🌾", s: "Nov–Mar", r: "UP, Rajasthan" },
        { n: "Oats", e: "🌾", s: "Nov–Mar", r: "Punjab" },
    ],
    "பருப்புகள் | Pulses": [
        { n: "கடலை | Chickpea", e: "🫘", s: "Nov–Feb", r: "MP, Rajasthan" },
        { n: "துவரை | Pigeon Pea", e: "🫘", s: "Jun–Sep", r: "Maharashtra" },
        { n: "உளுந்து | Black Gram", e: "🫘", s: "Jun–Sep", r: "All India" },
        { n: "பயறு | Green Gram", e: "🫘", s: "Jun–Sep", r: "All India" },
        { n: "மசூர் | Lentil", e: "🫘", s: "Nov–Feb", r: "MP, UP" },
        { n: "ராஜ்மா | Kidney Bean", e: "🫘", s: "Nov–Feb", r: "Himachal" },
        { n: "காராமணி | Cowpea", e: "🫘", s: "Jun–Sep", r: "All India" },
        { n: "கொள்ளு | Horse Gram", e: "🫘", s: "Jun–Sep", r: "South India" },
        { n: "அவரை | Cluster Bean", e: "🫘", s: "Jun–Sep", r: "Rajasthan" },
        { n: "Soybean", e: "🫘", s: "Jun–Sep", r: "MP, Maharashtra" },
        { n: "Field Pea", e: "🫘", s: "Nov–Feb", r: "UP, MP" },
        { n: "Moth Bean", e: "🫘", s: "Jun–Sep", r: "Rajasthan" },
    ],
    "எண்ணெய் வித்துகள் | Oilseeds": [
        { n: "நிலக்கடலை | Groundnut", e: "🥜", s: "Jun–Sep", r: "Gujarat, AP" },
        { n: "கடுகு | Mustard", e: "🌿", s: "Nov–Feb", r: "Rajasthan, UP" },
        { n: "எள் | Sesame", e: "🌿", s: "Jun–Sep", r: "Gujarat, WB" },
        { n: "சூரியகாந்தி | Sunflower", e: "🌻", s: "All year", r: "Karnataka" },
        { n: "ஆமணக்கு | Castor", e: "🌿", s: "Jun–Sep", r: "Gujarat, AP" },
        { n: "தேங்காய் | Coconut", e: "🥥", s: "Perennial", r: "Kerala, TN" },
        { n: "பனை | Palm Oil", e: "🌴", s: "Perennial", r: "AP, Telangana" },
        { n: "Linseed", e: "🌿", s: "Nov–Feb", r: "MP, CG" },
        { n: "Safflower", e: "🌼", s: "Nov–Feb", r: "Maharashtra" },
        { n: "Niger (Ramtil)", e: "🌿", s: "Jun–Sep", r: "Odisha, CG" },
        { n: "Rapeseed", e: "🌿", s: "Nov–Feb", r: "North India" },
    ],
    "வணிக பயிர்கள் | Cash Crops": [
        { n: "கரும்பு | Sugarcane", e: "🎋", s: "Annual", r: "UP, Maharashtra" },
        { n: "பருத்தி | Cotton", e: "🌸", s: "Jun–Sep", r: "Gujarat, Maharashtra" },
        { n: "சணல் | Jute", e: "🌿", s: "Mar–Jun", r: "WB, Bihar" },
        { n: "தேயிலை | Tea", e: "🍵", s: "Perennial", r: "Assam, Kerala" },
        { n: "காபி | Coffee", e: "☕", s: "Perennial", r: "Karnataka" },
        { n: "ரப்பர் | Rubber", e: "🌳", s: "Perennial", r: "Kerala" },
        { n: "Tobacco", e: "🌿", s: "Both", r: "AP, Gujarat" },
        { n: "Hemp", e: "🌿", s: "Jun–Sep", r: "Uttarakhand" },
    ],
    "காய்கறிகள் | Vegetables": [
        { n: "தக்காளி | Tomato", e: "🍅", s: "All year", r: "AP, Maharashtra" },
        { n: "வெங்காயம் | Onion", e: "🧅", s: "Both", r: "Maharashtra" },
        { n: "உருளை | Potato", e: "🥔", s: "Nov–Feb", r: "UP, WB" },
        { n: "கத்திரி | Brinjal", e: "🍆", s: "All year", r: "WB, Odisha" },
        { n: "மிளகாய் | Chilli", e: "🌶️", s: "Jun–Sep", r: "AP, Karnataka" },
        { n: "வெண்டை | Okra", e: "🌿", s: "All year", r: "All India" },
        { n: "பூண்டு | Garlic", e: "🧄", s: "Nov–Feb", r: "MP, Gujarat" },
        { n: "இஞ்சி | Ginger", e: "🫚", s: "Jun–Sep", r: "Kerala" },
        { n: "பீட்ரூட் | Beetroot", e: "🫀", s: "Nov–Feb", r: "All India" },
        { n: "கேரட் | Carrot", e: "🥕", s: "Nov–Feb", r: "Punjab, HP" },
        { n: "காலிஃப்ளவர் | Cauliflower", e: "🥦", s: "Nov–Feb", r: "WB, Bihar" },
        { n: "கோஸ் | Cabbage", e: "🥬", s: "Nov–Feb", r: "WB, Assam" },
        { n: "பரங்கி | Pumpkin", e: "🎃", s: "Jun–Sep", r: "All India" },
        { n: "வெள்ளரி | Cucumber", e: "🥒", s: "Summer", r: "All India" },
        { n: "முருங்கை | Drumstick", e: "🌿", s: "Perennial", r: "TN, AP" },
        { n: "பீன்ஸ் | Beans", e: "🫛", s: "All year", r: "All India" },
        { n: "சர்க்கரைவள்ளி | Sweet Potato", e: "🍠", s: "Jun–Sep", r: "Odisha" },
        { n: "வாழைத்தண்டு | Banana Stem", e: "🌿", s: "Perennial", r: "TN, AP" },
        { n: "குடைமிளகாய் | Capsicum", e: "🫑", s: "All year", r: "HP, Karnataka" },
        { n: "Broccoli", e: "🥦", s: "Nov–Feb", r: "HP" },
        { n: "Spinach", e: "🥬", s: "Nov–Feb", r: "All India" },
        { n: "Bitter Gourd", e: "🫑", s: "Summer", r: "All India" },
        { n: "Bottle Gourd", e: "🫙", s: "Summer", r: "All India" },
        { n: "Snake Gourd", e: "🌿", s: "Jun–Sep", r: "South India" },
        { n: "Ash Gourd", e: "🫙", s: "Jun–Sep", r: "All India" },
        { n: "Ridge Gourd", e: "🌿", s: "Jun–Sep", r: "All India" },
        { n: "Radish", e: "🌱", s: "Nov–Feb", r: "North India" },
        { n: "Turnip", e: "🌱", s: "Nov–Feb", r: "Punjab, HP" },
        { n: "Coriander", e: "🌿", s: "Nov–Feb", r: "Rajasthan" },
        { n: "Mint", e: "🌿", s: "Summer", r: "UP, Punjab" },
        { n: "Fenugreek", e: "🌿", s: "Nov–Feb", r: "Rajasthan" },
        { n: "Celery", e: "🌿", s: "Nov–Feb", r: "HP" },
        { n: "Leek", e: "🧅", s: "Nov–Feb", r: "North India" },
        { n: "Yam", e: "🍠", s: "Jun–Sep", r: "South India" },
        { n: "Colocasia", e: "🌿", s: "Jun–Sep", r: "All India" },
        { n: "Elephant Foot Yam", e: "🍠", s: "Jun–Sep", r: "Kerala" },
    ],
    "பழங்கள் | Fruits": [
        { n: "மாம்பழம் | Mango", e: "🥭", s: "Summer", r: "UP, AP" },
        { n: "வாழை | Banana", e: "🍌", s: "Perennial", r: "TN, AP" },
        { n: "திராட்சை | Grapes", e: "🍇", s: "Annual", r: "Maharashtra" },
        { n: "கொய்யா | Guava", e: "🍐", s: "All year", r: "UP, MP" },
        { n: "பப்பாளி | Papaya", e: "🍈", s: "All year", r: "AP, TN" },
        { n: "மாதுளை | Pomegranate", e: "🍎", s: "All year", r: "Maharashtra" },
        { n: "ஆரஞ்சு | Orange", e: "🍊", s: "All year", r: "Nagpur" },
        { n: "எலுமிச்சை | Lemon", e: "🍋", s: "All year", r: "AP, Gujarat" },
        { n: "அன்னாசி | Pineapple", e: "🍍", s: "All year", r: "Kerala, Assam" },
        { n: "சப்போட்டா | Sapota", e: "🍑", s: "All year", r: "Gujarat, AP" },
        { n: "பலாப்பழம் | Jackfruit", e: "🍈", s: "Summer", r: "Kerala, TN" },
        { n: "Avocado", e: "🥑", s: "Summer", r: "TN, Kerala" },
        { n: "லிட்சி | Litchi", e: "🍒", s: "Summer", r: "Bihar, WB" },
        { n: "ஆப்பிள் | Apple", e: "🍎", s: "Summer", r: "HP, J&K" },
        { n: "பேரி | Pear", e: "🍐", s: "Summer", r: "HP, J&K" },
        { n: "பிளம் | Plum", e: "🍑", s: "Summer", r: "HP" },
        { n: "ஸ்ட்ராபெர்ரி | Strawberry", e: "🍓", s: "Winter", r: "HP, Maharashtra" },
        { n: "Kiwi", e: "🥝", s: "Annual", r: "HP, Arunachal" },
        { n: "Dragon Fruit", e: "🍈", s: "All year", r: "Karnataka" },
        { n: "ஆமலா | Amla", e: "🍏", s: "Annual", r: "UP, MP" },
        { n: "நெல்லி | Tamarind", e: "🌿", s: "Perennial", r: "AP, TN" },
        { n: "வால்நட் | Walnut", e: "🌰", s: "Annual", r: "J&K, HP" },
        { n: "Cherry", e: "🍒", s: "Summer", r: "J&K, HP" },
        { n: "Custard Apple", e: "🍏", s: "Summer", r: "AP, Gujarat" },
        { n: "Jamun", e: "🫐", s: "Summer", r: "All India" },
    ],
    "மசாலா | Spices": [
        { n: "மிளகு | Black Pepper", e: "🌶️", s: "Perennial", r: "Kerala" },
        { n: "ஏலக்காய் | Cardamom", e: "🌿", s: "Perennial", r: "Kerala" },
        { n: "மஞ்சள் | Turmeric", e: "🟡", s: "Jun–Sep", r: "AP, Odisha" },
        { n: "சீரகம் | Cumin", e: "🌿", s: "Nov–Feb", r: "Rajasthan" },
        { n: "கொத்தமல்லி | Coriander Seed", e: "🌿", s: "Nov–Feb", r: "Rajasthan" },
        { n: "சோம்பு | Fennel", e: "🌿", s: "Nov–Feb", r: "Gujarat" },
        { n: "கிராம்பு | Clove", e: "🌿", s: "Perennial", r: "Kerala" },
        { n: "இலவங்கம் | Cinnamon", e: "🌿", s: "Perennial", r: "Kerala" },
        { n: "ஜாதிக்காய் | Nutmeg", e: "🌰", s: "Perennial", r: "Kerala" },
        { n: "வெனிலா | Vanilla", e: "🌸", s: "Perennial", r: "Karnataka" },
        { n: "குங்குமப்பூ | Saffron", e: "🌸", s: "Annual", r: "J&K" },
        { n: "கரும்புளி | Star Anise", e: "⭐", s: "Perennial", r: "Arunachal" },
        { n: "Ajwain", e: "🌿", s: "Nov–Feb", r: "Rajasthan" },
        { n: "Asafoetida", e: "🌿", s: "Rabi", r: "Kashmir" },
    ],
    "பூக்கள் | Flowers": [
        { n: "ரோஜா | Rose", e: "🌹", s: "All year", r: "Karnataka, TN" },
        { n: "மல்லிகை | Jasmine", e: "🌸", s: "All year", r: "TN, Karnataka" },
        { n: "சேவந்தி | Marigold", e: "🌼", s: "All year", r: "All India" },
        { n: "தாமரை | Lotus", e: "🪷", s: "All year", r: "WB, Bihar" },
        { n: "Gladiolus", e: "🌷", s: "All year", r: "Karnataka" },
        { n: "Gerbera", e: "🌻", s: "All year", r: "Karnataka" },
        { n: "Chrysanthemum", e: "🌼", s: "All year", r: "TN" },
        { n: "Tuberose", e: "🌸", s: "All year", r: "TN" },
        { n: "வெற்றிலை | Betel Leaf", e: "🍃", s: "Perennial", r: "WB, Odisha" },
        { n: "பாக்கு | Areca Nut", e: "🌴", s: "Perennial", r: "Karnataka" },
        { n: "முந்திரி | Cashew", e: "🌰", s: "Annual", r: "Kerala, Goa" },
    ],
};

export const ALL_CROP_LIST = Object.values(CROPS).flat();
export const ALL_CROP_NAMES = ALL_CROP_LIST.map(c => c.n);
export const CROP_EMOJI_MAP = ALL_CROP_LIST.reduce((a, c) => { a[c.n] = c.e; return a; }, {});
